Repository NHSDigital/Galleri-Invitations, pull requests merged in 2023-11, with the labels that each got.

#84 Gal 211/load pseudonymised data to caas datastore
  .github/workflows/stage-2-test.yaml
  .github/workflows/stage-4-acceptance.yaml
  package-lock.json
  package.json
  scripts/generatePersonTestData/README.txt
  scripts/generatePersonTestData/generatePersonTestData.js
  scripts/generatePersonTestData/package-lock.json
  scripts/generatePersonTestData/package.json
  scripts/generatePersonTestData/run.sh
  scripts/generatePersonTestData/utility.js
  scripts/pipeline/nonprod_population_load/nonprod_population_load.py
  scripts/pipeline/seed-data.sh
  scripts/pipeline/unit_tests/nonprod_population_load_test.py
  scripts/pipeline/unit_tests/test_nonprod_lsoa_load.py
  scripts/pipeline/unit_tests/test_nonprod_population_load.py
Labels: javascript

#105 Refactor: CORS on fail case
  terraform/src/clinicIcbListLambda/clinicIcbListLambda.js
  terraform/src/clinicInformationLambda/clinicInformationLambda.js
  terraform/src/clinicSummaryListLambda/clinicSummaryListLambda.js
  terraform/src/getLsoaInRangeLambda/getLsoaInRangeLambda.js
  terraform/src/invitationParametersLambda/invitationParametersLambda.js
  terraform/src/invitationParametersPutForecastUptakeLambda/invitationParametersPutForecastUptakeLambda.js
  terraform/src/invitationParametersPutQuintilesLambda/invitationParametersPutQuintilesLambda.js
  terraform/src/participatingIcbListLambda/participatingIcbListLambda.js
  terraform/src/targetFillToPercentageLambda/targetFillToPercentageLambda.js
  terraform/src/targetFillToPercentagePutLambda/targetFillToPercentagePutLambda.js
Labels: refactor

#102 Hotfix/gal 473
  scripts/test_data/generateLsoaMidpoint/generateLsoaMidpoint.js
  scripts/test_data/generateLsoaMidpoint/generateLsoaMidpoint.test.js
  scripts/test_data/generateLsoaMidpoint/generatePersonTestData.js
  scripts/test_data/generateLsoaMidpoint/package-lock.json
  scripts/test_data/generateLsoaMidpoint/package.json
  scripts/test_data/generateLsoaMidpoint/utils/helper.js
  scripts/test_data/generatePersonTestData/README.txt
  scripts/test_data/generatePersonTestData/generatePersonTestData.js
  scripts/test_data/generatePersonTestData/package-lock.json
  scripts/test_data/generatePersonTestData/package.json
  scripts/test_data/generatePersonTestData/run.sh
  scripts/test_data/generatePersonTestData/utility.js
  scripts/test_data/generateUniqueLsoaFile/package-lock.json
  scripts/test_data/generateUniqueLsoaFile/package.json
  scripts/test_data/generateUniqueLsoaFile/uploadUniqueLsoas.js
  scripts/test_data/lsoaToParticipant/addLsoaToParticipant.js
  scripts/test_data/lsoaToParticipant/package-lock.json
  scripts/test_data/lsoaToParticipant/package.json
Labels: bug

#117 Updated phlebotomy clinic load python script to now included fillToTa…
  scripts/pipeline/nonprod_phlebotomy_site_load/nonprod_phlebotomy_site_load.py
Labels: aws

#128 Feature/gal 313
  scripts/pipeline/nonprod_unique_lsoa_load/nonprod_unique_lsoa_load.py
  scripts/test_data/updateForecastUptakeMod/package-lock.json
  scripts/test_data/updateForecastUptakeMod/package.json
  scripts/test_data/updateForecastUptakeMod/updateForecastUptakeMod.js
  scripts/test_data/updateForecastUptakeMod/updateForecastUptakeMod.test.js
  scripts/test_data/updateForecastUptakeMod/utils/helper.js
  terraform/main.tf
Labels: javascript

#126 Feature/gal 695/trigger episode record creation
  .github/actions/terraform/action.yaml
  scripts/pipeline/nonprod_population_load/nonprod_population_load.py
  scripts/pipeline/unit_tests/test_nonprod_population_load.py
  terraform/main.tf
  terraform/modules/iam_galleri_role/iam.tf
  terraform/src/generateInvitesTriggerLambda/generateInvitesTriggerLambda.js
  terraform/src/generateInvitesTriggerLambda/package-lock.json
  terraform/src/generateInvitesTriggerLambda/package.json
  terraform/src/tests/unitTests/generateInvitesTriggerLambda.test.js
Labels: javascript

#131 calculate number to invite
  .github/actions/terraform/action.yaml
  .gitignore
  package-lock.json
  package.json
  scripts/pipeline/nonprod_phlebotomy_site_load/nonprod_phlebotomy_site_load.py
  scripts/pipeline/nonprod_population_load/nonprod_population_load.py
  scripts/pipeline/nonprod_unique_lsoa_load/nonprod_unique_lsoa_load.py
  scripts/pipeline/unit_tests/test_nonprod_population_load.py
  scripts/pipeline/unit_tests/test_nonprod_unique_lsoa_load.py
  terraform/main.tf
  terraform/modules/iam_galleri_role/iam.tf
  terraform/src/calculateNumberToInviteLambda/calculateNumberToInviteLambda.js
  terraform/src/calculateNumberToInviteLambda/package-lock.json
  terraform/src/calculateNumberToInviteLambda/package.json
  terraform/src/clinicIcbListLambda/clinicIcbListLambda.js
  terraform/src/clinicSummaryListLambda/clinicSummaryListLambda.js
  terraform/src/generateInvitesTriggerLambda/generateInvitesTriggerLambda.js
  terraform/src/generateInvitesTriggerLambda/package-lock.json
  terraform/src/generateInvitesTriggerLambda/package.json
  terraform/src/getLsoaInRangeLambda/getLsoaInRangeLambda.js
  terraform/src/getLsoaParticipantsLambda/getLsoaParticipantsLambda.js
  terraform/src/tests/unitTests/calculateNumberToInviteLambda.test.js
  terraform/src/tests/unitTests/generateInvitesTriggerLambda.test.js
  terraform/src/tests/unitTests/getLsoaParticipantsLambda.test.js
Labels: enhancement, terraform, aws, javascript
