Repository NHSDigital/Galleri-Invitations, pull requests merged in 2024-02, with the labels that each got.

#269 Feature/gal 447/update person record
  .github/actions/terraform/action.yaml
  terraform/main.tf
  terraform/src/caasFeedUpdateRecordsLambda/caasFeedUpdateRecordsLambda.js
  terraform/src/caasFeedUpdateRecordsLambda/package-lock.json
  terraform/src/caasFeedUpdateRecordsLambda/package.json
  terraform/src/createEpisodeRecords/createEpisodeRecords.js
  terraform/src/tests/unitTests/caasFeedUpdateRecords.test.js
Labels: enhancement, javascript

#276 Feature/gal 345
  .github/actions/terraform/action.yaml
  jest.config.json
  package-lock.json
  package.json
  terraform/main.tf
  terraform/modules/iam_galleri_role/iam.tf
  terraform/src/gtmsMeshMailboxLambda/gtmsMeshMailboxLambda.js
  terraform/src/gtmsMeshMailboxLambda/helper.js
  terraform/src/gtmsMeshMailboxLambda/package-lock.json
  terraform/src/gtmsMeshMailboxLambda/package.json
  terraform/src/tests/unitTests/gtmsMeshMailboxLambda.test.js
  terraform/src/tests/unitTests/gtmsMeshMailboxLambdaSecret.test.js
Labels: aws, javascript

#293 Feature/gal 431
  .github/actions/terraform/action.yaml
  scripts/pipeline/nonprod_population_load/nonprod_population_load.py
  terraform/main.tf
  terraform/modules/dynamodb_stream/dynamodb_stream.tf
  terraform/modules/dynamodb_stream/variables.tf
  terraform/modules/iam_galleri_role/iam.tf
  terraform/src/createInvitationBatchLambda/createInvitationBatchLambda.js
  terraform/src/createInvitationBatchLambda/package.json
  terraform/src/gtmsUploadClinicDataLambda/gtmsUploadClinicDataLambda.js
  terraform/src/gtmsUploadClinicDataLambda/package-lock.json
  terraform/src/gtmsUploadClinicDataLambda/package.json
  terraform/src/tests/unitTests/createInvitationBatchLambda.test.js
  terraform/src/tests/unitTests/gtmsUploadClinicDataLambda.test.js
Labels: aws, javascript

#266 Feature/master person index end to end
  .github/actions/terraform/action.yaml
  .gitignore
  package-lock.json
  package.json
  scripts/config/.gitleaks.toml
  terraform/.terraform.lock.hcl
  terraform/main.tf
  terraform/modules/iam_galleri_role/iam.tf
  terraform/src/caasFeedAddRecordsLambda/caasFeedAddRecordsLambda.js
  terraform/src/caasFeedAddRecordsLambda/package-lock.json
  terraform/src/caasFeedAddRecordsLambda/package.json
  terraform/src/caasFeedUpdateRecordsLambda/caasFeedUpdateRecordsLambda.js
  terraform/src/caasFeedUpdateRecordsLambda/package-lock.json
  terraform/src/caasFeedUpdateRecordsLambda/package.json
  terraform/src/createEpisodeRecords/createEpisodeRecords.js
  terraform/src/pollMeshMailboxLambda/helper.js
  terraform/src/pollMeshMailboxLambda/package-lock.json
  terraform/src/pollMeshMailboxLambda/package.json
  terraform/src/pollMeshMailboxLambda/pollMeshMailboxLambda.js
  terraform/src/sendSingleMessageToParticipantLambda/package-lock.json
  terraform/src/tests/unitTests/caasFeedAddRecords.test.js
  terraform/src/tests/unitTests/caasFeedUpdateRecords.test.js
  terraform/src/tests/unitTests/pollMeshMailboxLambda.test.js
  terraform/src/tests/unitTests/validateCaasFeed.test.js
  terraform/src/validateCaasFeedLambda/package-lock.json
  terraform/src/validateCaasFeedLambda/package.json
  terraform/src/validateCaasFeedLambda/validateCaasFeedLambda.js
Labels: enhancement, aws, javascript

#320 Bug/gal 970/batch id conflicts
  terraform/src/createEpisodeRecords/createEpisodeRecords.js
  terraform/src/tests/unitTests/createEpisodeRecords.test.js
Labels: bug, aws, javascript
