Repository NHSDigital/Galleri-Invitations, pull requests merged in 2024-03, with the labels that each got.

#318 Feature/gal 1129
  terraform/main.tf
  terraform/modules/iam_galleri_role/iam.tf
  terraform/src/gtmsMeshMailboxLambda/gtmsMeshMailboxLambda.js
  terraform/src/gtmsMeshMailboxLambda/helper.js
  terraform/src/tests/unitTests/gtmsMeshMailboxLambda.test.js
Labels: aws, javascript, refactor

#321 Feature/gal 917/episode events caas deceased
  terraform/main.tf
  terraform/src/caasFeedUpdateRecordsLambda/caasFeedUpdateRecordsLambda.js
Labels: enhancement, aws, javascript

#306 Feature/gal 448/merge person record
  terraform/main.tf
  terraform/src/caasFeedUpdateRecordsLambda/caasFeedUpdateRecordsLambda.js
  terraform/src/getLsoaParticipantsLambda/getLsoaParticipantsLambda.js
Labels: aws, javascript

#350 hotfix/caasCert# resolving issue with polling lambda point to caas ma…
  terraform/main.tf
  terraform/src/pollMeshMailboxLambda/pollMeshMailboxLambda.js
Labels: bug, javascript

#355 hotfix/CaaSChunking# resolved connection issue, undefined count and c…
  terraform/src/pollMeshMailboxLambda/package-lock.json
  terraform/src/pollMeshMailboxLambda/pollMeshMailboxLambda.js
Labels: bug, aws

#361 Feature/GAL-152
  .github/actions/terraform/action.yaml
  scripts/test/api-test.js
  terraform/main.tf
  terraform/modules/iam_galleri_role/iam.tf
  terraform/src/gtmsStatusUpdateLambda/gtmsStatusUpdateLambda.js
  terraform/src/gtmsStatusUpdateLambda/package-lock.json
  terraform/src/gtmsStatusUpdateLambda/package.json
  terraform/src/tests/unitTests/gtmsStatusUpdateLambda.test.js
Labels: enhancement, aws, javascript

#381 Hotfix/validate caas indexing
  terraform/main.tf
  terraform/src/pollMeshMailboxLambda/pollMeshMailboxLambda.js
  terraform/src/validateCaasFeedLambda/validateCaasFeedLambda.js
Labels: bug

#395 Feature/gal 718
  .github/actions/terraform/action.yaml
  terraform/main.tf
  terraform/modules/iam_galleri_role/iam.tf
  terraform/src/appointmentsEventCancelledLambda/appointmentsEventCancelledLambda.js
  terraform/src/appointmentsEventCancelledLambda/package-lock.json
  terraform/src/appointmentsEventCancelledLambda/package.json
  terraform/src/tests/unitTests/appointmentsEventCancelledLambda.test.js
Labels: enhancement, aws, javascript

#338 Feature/gal 1177/add episode history
  .github/actions/terraform/action.yaml
  package.json
  terraform/main.tf
  terraform/modules/dynamodb_stream/dynamodb_stream.tf
  terraform/modules/dynamodb_stream/variables.tf
  terraform/modules/iam_galleri_role/iam.tf
  terraform/src/addEpisodeHistoryLambda/addEpisodeHistoryLambda.js
  terraform/src/addEpisodeHistoryLambda/package-lock.json
  terraform/src/addEpisodeHistoryLambda/package.json
  terraform/src/tests/unitTests/addEpisodeHistoryLambda.test.js
Labels: aws, javascript
